# Generated by Django 3.2.3 on 2022-01-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congressperson',
            name='termsServed',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
